pipeline {
    environment {
        def mavenHome = tool name:"Maven-3.6.1", type:"maven"
        def mavenCMD = "${mavenHome}/bin/mvn"
	DOCKER_REGISTRY_CREDENTIALS = credentials('DOCKER_REGISTRY_CREDENTIALS')
    }
    
    agent any

    stages {
        stage('Git Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/ngtrainings/HelloWorld/'
            }
        }
        stage('Maven clean build') {
            steps {
                bat "${mavenCMD} -f springboot-helloworld-master/pom.xml clean install"
            }
        }
        stage('Build Docker Images') {
            steps {
		bat "docker build -f springboot-helloworld-master/Dockerfile-Spring -t ngtrainings/springboot-helloworld-master:v4 ."
            }
        }
	stage('Docker Images push to Registory') {
            steps {
		bat "docker login -u ${DOCKER_REGISTRY_CREDENTIALS_USR} -p ${DOCKER_REGISTRY_CREDENTIALS_PSW}"
                bat "docker push ngtrainings/springboot-helloworld-master:v4"        	
            }
        }
	stage('Deploy docker Images in k8s') {
            steps {
		bat "kubectl apply -f springboot-helloworld-master/helloworld.yaml"
            }
        }
    }
}
