kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: sb-ingress
spec:
  rules:
  - http:
      paths:
      - path: /home
        backend:
          serviceName: springboot-helloworld-v5
          servicePort: 8080
      - path: /ingress
        backend:
          serviceName: springboot-helloworld-v6
          servicePort: 8080