apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: ngtrainings/springboot-helloworld-master:v1
          ports:
            - containerPort: 2020
          imagePullPolicy: Always