apiVersion: v1
kind: Secret
metadata:
  name: maria-secret
type: Opaque
data:
    username: dXNlcg==
    password: cGFzcw==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: maria-dep
    spec:
      containers:
        - name: maria-dep
          image: 'mariadb:10.4'
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_USER
            valueFrom:
                secretKeyRef:
                    name: maria-secret
                    key: username
          - name: MYSQL_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: maria-secret
                    key: password
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: maria-secret
                    key: password                    
          - name: MYSQL_DATABASE
            value: demodb
            

---
apiVersion: v1
kind: Service
metadata:
  name: maria-svc
  labels:
    name: maria-dep
spec:
  selector:
    app: maria-dep
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP