apiVersion: v1
kind: Secret
metadata:
  name: postgress-secret
type: Opaque
data:
    username: dXNlcg==
    password: cGFzcw==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgress-dep
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgress-dep
    spec:
      containers:
        - name: postgress-dep
          image: 'postgres'
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
                secretKeyRef:
                    name: postgress-secret
                    key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                    name: postgress-secret
                    key: password
          - name: POSTGRES_DB
            value: pdb

---
apiVersion: v1
kind: Service
metadata:
  name: postgress-svc
  labels:
    name: postgress-dep
spec:
  selector:
    app: postgress-dep
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP